version: "3"
services:
    app:
        build: ./docker/app
        volumes:
            - ../:/workspace:cached
        ports:
            - 80:80
        tty: true
        environment:
            APP_ENV: local
            PHP_EXTENSION_XDEBUG: 1
            PHP_EXTENSION_PGSQL: 1
            PHP_EXTENSION_PDO_PGSQL: 1
            APACHE_DOCUMENT_ROOT: /workspace/public

